# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1
  - name: project & Publication 
    url: tags/
    weight: 4
  - name: Certificates
    url: certificates/
    weight: 3
  - name: Achievements
    url: achievements/
    weight: 2
  - name: Freelance work
    url: freelance-work/
    weight: 5




