# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: الريسية
    url: /
    weight: 10

  - name: الإنجازات
    url: achievements/
    weight: 20

  - name: الشهادات
    url: certificates/
    weight: 30

  - name: المدونة
    url: blog/
    weight: 35

  - name: الأعمال
    url: tags/
    weight: 40

  - name: المشاريع
    identifier: projects
    url: /projects/
    weight: 60

  - name: جميع المشاريع
    parent: projects
    url: /projects/
    weight: 61

  - name: المشاريع المميزة
    parent: projects
    url: /projects-featured/
    weight: 62

  - name: مشاريع العملاء
    parent: projects
    url: /projects-clients/
    weight: 63

  - name: المشاريع مفتوحة المصدر
    parent: projects
    url: /projects-opensource/
    weight: 64

  - name: المشاريع البحثية
    parent: projects
    url: /projects-research/
    weight: 65