# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
    
  - name: Achievements
    url: achievements/
    weight: 20

  - name: Certificates
    url: certificates/
    weight: 30

  - name: المدونة
    url: blog/
    weight: 35

  - name: Works 
    url: tags/
    weight: 40

  - name: Projects
    identifier: projects
    url: projects/
    weight: 60
    main:
  - name: My Projects list
    parent: projects
    URL: Projects/
    weight: 103
  - name: Hobby projects
    parent: projects
    URL: projects-w1/
    weight: 103
  - Name: Published Projects
    URL: published-projects/
    parent: projects
    weight: 102
  - name: Freelance Work
    url: freelance-work/
    parent: projects
    weight: 101











