# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1
  - name: all my work 
    url: tags/
    weight: 4
  - name: Certificates
    url: certificates/
    weight: 3
  - name: Achievements
    url: achievements/
    weight: 2
  - name: Freelance work
    url: freelance-work/
    weight: 5

- name: my projects
    url: projects/
    weight: 6
- name: more
    url: prokects-w1/
    weight: 7
- name: published projects
    url: published-projects/
    weight: 8




