# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10

  - name: Articles
    identifier: articles
    url: /blog/
    weight: 20

  - name: Topics
    url: /tags/
    weight: 30

  - name: Projects
    url: /projects/
    weight: 40

  - name: Achievements
    url: /achievements/
    weight: 50

  - name: Certificates
    url: /certificates/
    weight: 60

  - name: Articles
    parent: articles
    url: /articles/
    weight: 21

  - name: Education
    parent: articles
    url: /education/
    weight: 22

  - name: Posts
    parent: articles
    url: /posts/
    weight: 23
