# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: الريسية
    url: /
    weight: 10

  - name: المقالات
    identifier: articles
    url: /blog/
    weight: 20

  - name: اعمالي
    url: /tags/
    weight: 30

  - name: المشاريع
    url: /projects/
    weight: 40

  - name: الإنجازات
    url: /achievements/
    weight: 50

  - name: الشهادات
    url: /certificates/
    weight: 60

  - name: المدونة
    parent: articles
    url: /articles/
    weight: 21

  - name: تعليم وكورسات
    parent: articles
    url: /education/
    weight: 22

  - name: الأخبار
    parent: articles
    url: /posts/
    weight: 23