# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: project & Publication 
    url: tags/
    weight: 50
  - name: Certificates
    url: certificates/
    weight: 30
  - name: Achievements
    url: Achievements/
    weight: 30
