appearance:
  mode: dark
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'للمهندس خالد حميدي كنو (Khaled HAMIDI KENO)، خبير في الميكاترونيكس وهندسة الطيران، ومطور أنظمة ذكية. متخصص في تصميم الأنظمة المعقدة، الذكاء الاصطناعي، والروبوتات المتقدمة. مؤسس فريق Robotech ومهندس حلول تقنية عالية'
    twitter: 'engkhamidi'
  analytics:
    google_analytics: 'G-0FK610BF9E'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Khaled HAMIDI. This work is licensed under CC BY-NC-ND 4.0'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Social media links
social:
  linkedin: 'https://www.linkedin.com/in/enghamidi/'
  twitter: 'https://twitter.com/engkhamidi'
  github: 'https://github.com/khaledHamidi'
  facebook: 'https://www.facebook.com/eng.khaled.hamidi'
  instagram: 'https://www.instagram.com/engkhamidi/'
  youtube: 'https://www.youtube.com/@enghamidi'
  researchgate: 'https://www.researchgate.net/profile/Khaled-Hamidi-2'
  orcid: 'https://orcid.org/0009-0004-2962-0833'
  google_scholar: 'https://scholar.google.com/citations?user=tto5XMQAAAAJ'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: ...
    content_dir: ...
    branch: ...
i_am_a_sponsor: true
power_ups:
  hide_published_with: true

plugins:
  css:
    - link: assets/css/custom.css
  js:
    - link: assets/js/custom-search.js
